%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 500.71 
Camera.fy: 501.09
Camera.cx: 241.60
Camera.cy: 318.27

Camera.k1: 0.16286688566078966
Camera.k2: -0.4411611742037365
Camera.p1: -0.0005966911545506503
Camera.p2: -0.0006828332032098936

# Camera.fx: 1000
# Camera.fy: 1000
# Camera.cx: 376
# Camera.cy: 240

# Camera.k1: 0
# Camera.k2: 0
# Camera.p1: 0
# Camera.p2: 0

# Camera resolution
Camera.width: 480
Camera.height: 640

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.9999769008332585, 0.004633040100445734, 0.004973202121122985, 0.0010876982667553613,
          0.004681946673720899, -0.999940350738196, -0.009867843782526925, 0.02605093199508686,
          0.004927187357338281, 0.009890900110686754, -0.9999389445959911, 0.0036296685716192796,
          0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 5.175e-04 #1.6968e-04 
IMU.NoiseAcc: 8.620e-03 #2.0e-3
IMU.GyroWalk: 3.003e-05 # 1.9393e-05 
IMU.AccWalk: 4.984e-04 # 3e-03
IMU.Frequency: 300


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5 # -1.8
Viewer.ViewpointF: 500

